# Generated by Django 4.1.5 on 2023-07-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('todoId', models.AutoField(primary_key=True, serialize=False)),
                ('todoContent', models.CharField(max_length=255)),
            ],
        ),
    ]
